### ISSUE TITLE
renaming of WMGM.py into process_data.py lost header comments

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/gm-challenge#11]
old function with header doc:
https://github.com/neuropoly/gm_challenge/blob/38897827db5ff73a7836f8e620f68f4d51ff5b54/WMGM.py

new renamed function without doc:
https://github.com/neuropoly/gm_challenge/blob/master/process_data.py

**Comment by stephaniealley** [comment]
I will resolve this once PR #25 has gone through.

**Comment by jcohenadad** [comment]
PR #25 is now merged-- i can take care of that one
