### ISSUE TITLE
Not all wm phantom values are equal

### ISSUE THREAD

**Issue by stephaniealley** [sct-pipeline/gm-challenge#19]
This is the reason that the contrast value for wm/gm=50/50 is not 0.
<img width="392" alt="screen shot 2018-05-23 at 5 23 53 pm" src="https://user-images.githubusercontent.com/32311792/40455632-e786dc2e-5ebb-11e8-8d62-78ac64cc4444.png">

**Comment by jcohenadad** [comment]
then you are not extracting values properly. You should either discard values with PVE, or use gaussian mixture modeling (e.g. ML or MAP offered by sct_extract_metric)

**Comment by jcohenadad** [comment]
the WM mask is way too big:
<img width="430" alt="screen shot 2018-05-28 at 17 34 58" src="https://user-images.githubusercontent.com/2482071/40605466-75b8eee4-629d-11e8-9dc3-20342e3e270d.png">

This is partly the reason for inaccurate WM extraction.

**Comment by jcohenadad** [comment]
fixed via #28
