### ISSUE TITLE
Add method for computing SNR from a single scan

### ISSUE THREAD

**Issue by stephaniealley** [sct-pipeline/gm-challenge#36]
Implement method as described in Griffanti et al., Biomed Sign Proc and Control, 2012.

https://www.sciencedirect.com/science/article/pii/S1746809411000565

**Comment by jcohenadad** [comment]
@stephaniealley i cannot find the paper easily-- pls add direct link to it

**Comment by stephaniealley** [comment]
The link has been added.

**Comment by jcohenadad** [comment]
@stephaniealley if your plan is to use SNR_single, as described in the paper (copied below):

> 2.3.1.1. Method 1—single ROI for signal and noise, single image. The
signal S is computed as the 2D mean value of the pixel intensities
inside ROIbody. Noise is computed as the 2D-SD of pixel intensity in
ROIbody [29]. SNR is computed with Eq. (2):

what is your plan to select the ROI_body, and how do you expect to mitigate for B1+ biases across scanners (e.g., B1+ different at 7T vs. 3T, hence the estimated SD is not shift-invariant)?

**Comment by stephaniealley** [comment]
@jcohenadad for the ROI_body, I was planning to use the wm as we did for SNR_diff.
