### ISSUE TITLE
Cord and GM segmentation should only be performed on the first scan

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/gm-challenge#4]
the 2nd scan is only used to compute SNR using the diff method, i.e.:
1. register scan 2 to scan 1
2. segment cord on scan 1
3. compute SNR using diff method between 1 and 2_reg

**Comment by stephaniealley** [comment]
Correct. The segmentations for the second scan are not necessary and should not be included.

**Comment by jcohenadad** [comment]
@stephaniealley what is the status of this issue?

**Comment by stephaniealley** [comment]
@jcohenadad this has already been resolved. I will close it.

**Comment by jcohenadad** [comment]
@stephaniealley in the future, when you fix an issue, close it by referring to the commit that fixes the issue-- thx

**Comment by stephaniealley** [comment]
Yes, of course. Sorry about that.

Stephanie

**Comment by jcohenadad** [comment]
reopening this issue because https://github.com/neuropoly/gm_challenge/pull/5 is not merged.
order should be:
- open issue
- fix issue
- open PR referencing issue
- close PR
- close issue

**Comment by stephaniealley** [comment]
Ah, ok, I see. Thank you for the clarification.

**Comment by stephaniealley** [comment]
This was resolved with PR #5.
