### ISSUE TITLE
Figuring out missing/additional datasets

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/gm-challenge#52]
From ~[this dataset](https://osf.io/5dqen/)~ [this dataset](https://github.com/sct-pipeline/gm-challenge-data), compared to the [current version of the manuscript](https://docs.google.com/document/d/1jDFZrpJ8nWunP9HjUTN5yDwT4cbnM5zaLDgDliLyMxc/edit), the following dataset is missing: 9671 (Olomouc) and the following are not included in the manuscript: 10062, 10063, 10328.

**Comment by jcohenadad** [comment]
Update: 10328 corresponds to Seif et al.
Note: this dataset only has one image (data2 is missing).

**Comment by jcohenadad** [comment]
OK I found in old notes that 10062, 10063 submissions are from Olomouc (Labounek et al). We now have three submissions from Olomouc so we need to figure out if we keep the three.

**Comment by renelabounek** [comment]
Original submission presented in Paris had interpolated in-plane resolution. That was decided to not present in the manuscript. Therefore, we submitted data of two similar protocols with in-plane resolutions 0.6×0.6mm2 and 0.7×0.7mm2 after Paris. If I remember well 0.6×0.6 protocol had better SNR and CNR values but also significantly higher acquisition time. 0.7×0.7mm2 was not so much worse and acquisition time was noticibly lower. In some comment in manuscript, you wrote that we can present both 0.6×0.6 nad 0.7×0.7 protocols. If we should select just one, I would need tolook again with Jan and others at SNR, CNR, etc. results and considering acquisition time.

@valosekj Do you know/remember something more than I do?

Are submissions 10062 and 10063 online available? To avoid a risk of switching images with another scans at my HDD.

**Comment by jcohenadad** [comment]
Thank you for the quick reply!

> In some comment in manuscript, you wrote that we can present both 0.6×0.6 nad 0.7×0.7 protocols. 

no problem then, we can keep both 😊 

> Are submissions 10062 and 10063 online available? To avoid a risk of switching images with another scans at my HDD.

yup! [here](https://github.com/sct-pipeline/gm-challenge-data)

**Comment by renelabounek** [comment]
I have got the data and can confirm that these submissions are our images acquired at same volunteer in the same day. And there is really acquisition time jump 0.7×0.7×2.5 about 3min 47s and 0.6×0.6×2.5 about 7min 56s. Graph of dependence of SNR/CNR at acquisition time / voxel volume should appear in the manuscript.

BTW & FYI: I am a bit sad that we all focused only on the best working t2* contrast and no one submitted t1 images with WM/GM contrast.

**Comment by jcohenadad** [comment]
> BTW & FYI: I am a bit sad that we all focused only on the best working t2* contrast and no one submitted t1 images with WM/GM contrast.

good point!

**Comment by valosekj** [comment]
Just for confirmation; I also checked the [current dataset](https://github.com/sct-pipeline/gm-challenge-data) and I can confirm that [10062](https://github.com/sct-pipeline/gm-challenge-data/tree/main/10062) and [10063](https://github.com/sct-pipeline/gm-challenge-data/tree/main/10063) are "Olomouc" submissions.

**Comment by renelabounek** [comment]
> Just for confirmation; I also checked the [current dataset](https://github.com/sct-pipeline/gm-challenge-data) and I can confirm that [10062](https://github.com/sct-pipeline/gm-challenge-data/tree/main/10062) and [10063](https://github.com/sct-pipeline/gm-challenge-data/tree/main/10063) are "Olomouc" submissions.

I would label datasets as "CEITEC" or "CEITEC-Brno" not "Olomouc". Data were acquired at the Prisma scanner in the CEITEC Brno. Therefore, it apears to me as more fair label.

**Comment by valosekj** [comment]
> > Just for confirmation; I also checked the [current dataset](https://github.com/sct-pipeline/gm-challenge-data) and I can confirm that [10062](https://github.com/sct-pipeline/gm-challenge-data/tree/main/10062) and [10063](https://github.com/sct-pipeline/gm-challenge-data/tree/main/10063) are "Olomouc" submissions.
> 
> I would label datasets as "CEITEC" or "CEITEC-Brno" not "Olomouc". Data were acquired at the Prisma scanner in the CEITEC Brno. Therefore, it apears to me as more fair label.

Agree! I think that this suggestion is also mentioned as a comment directly in the manuscript.

**Comment by jcohenadad** [comment]
Fixed via https://github.com/sct-pipeline/gm-challenge-data/pull/17
