### ISSUE TITLE
Wrong calculation of SNR_single

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/gm-challenge#58]
## Context

In #45 we replaced the code for SNR_single by SNR_mult, as implemented in SCT. The problem is that SNR_mult (computes STD over time) is _not_ the same thing as SNR_single (computes STD spatially).

## Solution

Implement a method in SCT to compute SNR using a single slice, and switch from SNR_mult to SNR_single in the present code.

**Comment by joshuacwnewton** [comment]
> In #45 we replaced the code for SNR_single by SNR_mult, as implemented in SCT. 

SNR_single is referring to the following function, right?

https://github.com/sct-pipeline/gm-challenge/blob/856d804ba41eb727a11889500cd61b3b4e736a90/process_data.py#L89-L116

**Comment by jcohenadad** [comment]
> SNR_single is referring to the following function, right?

So yes, it is referring to the following function, however I think I would like to slightly change the way the noise standard deviation is estimated: i am thinking instead of creating a small (eg 5x5 pixels) window at one (or several) corner(s) of the image and compute the STD from there. This is the more "traditional" method for it. And the mask would be used to compute the mean of the signal inside the region of interest (eg: the white matter), and divide this mean by the noise STD. This corresponds to the SNRstdv and SNRmean approaches described in [Dietrich et al. 2007](https://paperpile.com/app/p/d1f035d3-0f3c-00b4-9c5a-c4bf326a57ab). Note that the SNRstdv will need to be corrected for Rayleigh (as opposed to Gaussian) distributions (see equations A11 and A12 in the article).
