### ISSUE TITLE
Make a figure for the spine-generic dataset

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/gm-challenge#61]
@jcohenadad will generate SNR and contrast results from the [spine-generic multicenter data](https://zenodo.org/record/4299140#.YQKcNlNKjaQ). The output will be a CSV like [this one](https://github.com/sct-pipeline/gm-challenge/releases/download/v0.1/results.csv).

We need a script that takes this CSV as input and generates a figure like this one:
<img width="829" alt="Screen Shot 2021-07-29 at 8 15 47 AM" src="https://user-images.githubusercontent.com/2482071/127490390-172f8254-ab19-4959-b207-098872ae7298.png">

> Note: The figure above is only an illustration. At the end, there will be three distribution per xtick (not two, as in the figure above).

The library used to generate such plot is [RainCloudPlots](https://github.com/RainCloudPlots/RainCloudPlots#raincloud-plots).

The script will have to fetch the vendor (GE, Philips, Siemens) from the participants.tsv file of the spine-generic dataset. For inspiration, see [this script](https://github.com/spine-generic/spine-generic/blob/master/spinegeneric/cli/generate_figure.py)

Also, we need to figure out how to properly display the two y-axes (one for SNR one for contrast).

**Comment by jcohenadad** [comment]
> Also, we need to figure out how to properly display the two y-axes (one for SNR one for contrast).

Maybe we could simply make two separate figures: one for SNR and one for Contrast.

**Comment by alexfoias** [comment]
@jcohenadad Can I implement it on https://github.com/spine-generic/spine-generic since the input data is from spine-generic?

**Comment by jcohenadad** [comment]
> @jcohenadad Can I implement it on https://github.com/spine-generic/spine-generic since the input data is from spine-generic?

no, this is a different project (we don't want spine-generic repos to become a dump for the many future projects). We should have the script in this repos. You can call it eg `generate_figure_spinegeneric.py`
