### ISSUE TITLE
Add the Deamon file and other NiftyWeb-related files for future challenges

### ISSUE THREAD

**Issue by jcohenadad** [sct-pipeline/gm-challenge#8]
I think it would make sense to upload all related files and documentation that enabled us to link this challenge with the NiftyWeb platform, so that next we do it, we won't start from zero.

@stephaniealley I suggest you create a specific folder, with a README and the necessary files.

**Comment by stephaniealley** [comment]
@jcohenadad Yes, this was being done elsewhere (GDrive), but I will upload everything here.

**Comment by stephaniealley** [comment]
This has been resolved with commit 7f859f3.
